### ISSUE TITLE
Tidy up inbetween milestones

### ISSUE THREAD

**Issue by cjrace** [dfe-analytical-services/shinyGovstyle#124]
One to do at the end of the current milestone to avoid conflicts / issues with ongoing work. A few things I'd like to tidy up to avoid us tripping up over them in future. In particular, I've accidentally styled the code a couple of times from muscle memory (as we do that in our other package repos) and had to undo it as that can get us into a world of conflicts if we're not careful. Should also help readability and consistency with other code too

- [x] Run `styler::style_dir()` to apply tidyverse styling to whole repo
- [x] Add a commit hook for enforcing tidyverse code formatting
- [x] Update default branch from master to main
- [x] Set up dependabot alerts to track GDS version

Add more to the list above as you think of them...

**Comment by cjrace** [comment]
Holding off on these as we still have a few things in progress and I'm wary of conflicts (e.g. #152 / #93 / #138 / #150 ). Happy to pick up when I'm back though!

**Comment by sarahmwong** [comment]
Could set this up so we know when we're out of date with the gov.uk frontend?[ ](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates)

**Comment by cjrace** [comment]
> Could set this up so we know when we're out of date with the gov.uk frontend? [dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates)

Definitely!
